### PR TITLE
React rails project as one app with Webpack

### PR DESCRIPTION
**Pull request by eerapheal**
### Built with:

- Ruby on Rails
- Postgresql
- Capybera
- Rspec
- Cancancan
- Devise
- Webpack.
- React
- Redux

### Learning objectives

Implement a connection between a Ruby on Rails back-end and React front-end.
Understand the pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

### CODE REVIEW

**Comment by addod19** [comment]
### Hi @eerapheal, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because we did not follow the Git-flow work flow thus creating the PR branch from `webpack-rails` into the `dev` branch. Instead we followed the GitHub work flow

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by eerapheal** [comment]
@addod19 thanks for the review but I don't understand what you are explaining.

**Comment by addod19** [comment]
> @addod19 thanks for the review but I don't understand what you are explaining.

@eerapheal, thanks for reaching out. What i mean is that in this project, we are required to follow Git-flow when submitting our PR right? Git-flow is when we create a PR from let's say a branch called `rails_react` branch into the `Developer` branch in our case. When we do this, then we have followed Git-flow. I hope this is more clearer

**Comment by eerapheal** [comment]
I have done that already thanks.

**Pull request merged**
